---
  name: Release
  
  on:
    push:
      branches:
        - master
      paths:
        - lib/*.js
        - Dockerfile
        - test/**

  jobs:
    release:
      name: Release
      runs-on: ubuntu-latest
      environment: release
      steps:
        - uses: actions/checkout@v3
  
        - uses: actions/setup-node@v3
          with:
            node-version: '16.x'
  
        - run: npm ci
  
        - run: npm test
  
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
  
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GH_PAT_PUBLISH }}
  
        - name: Build and push the image to GitHub Registry
          uses: docker/build-push-action@v5
          with:
            context: "."
            push: true
            tags: ghcr.io/${{ github.repository }}/pull:latest
            build-args: |
              VCS_REF=${{ github.sha }}
              BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
            github-token: ${{ secrets.GH_PAT_PUBLISH }}
